# Generated by Django 2.2.7 on 2020-05-10 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
