# Generated by Django 2.2.7 on 2020-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='no_image.png', upload_to='movie_posters'),
        ),
    ]
