# Generated by Django 2.2.7 on 2020-05-13 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200513_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='year',
            new_name='released',
        ),
    ]
